### ISSUE TITLE
[staging] General Error flashing in frontend

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#215]
**Description**
There are a few of these that happen as a result of some of the data not being available when the UI is ready to render, but we're not properly handling the data not being available but when the data becomes available then the application re-renders which is why there's an error flash

**Steps to Reproduce**
1. Click on any Dataset listed
2. Click on "Back to Results" link
3. Pay attention to image

**Actual Results**
Application error image flashed when coming back to Browse Data page

**Expected Results**
This error flashing should not happened

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/54f70cc4-ab94-4803-b45f-e0733fa22e9c

**Comment by lauramarcos** [comment]
@codemonkey800 I experienced a couple of these flashing bugs today but I am not certain if I will find them again.. I will leave this open for now and keep checking... I cannot say this is fixed yet tho!

**Comment by lauramarcos** [comment]
@codemonkey800 I am still seeing these flashing errors, this evidence is from today


https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/e07aa613-a78a-4647-b395-a5f583c87ccf

**Comment by lauramarcos** [comment]
Happening when clicking on "Learn More" in Precision tooltip


https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/68fb8a42-92b9-4486-ad9d-18482eb731b9

**Comment by lauramarcos** [comment]
In production:

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/c548ea6b-8cca-44ef-9cb9-c9cee4cbdfe4

**Comment by jgadling** [comment]
This still happens fairly often for me in **firefox** and it doesn't just flash, but I get the error and I have to click "back" to proceed:
![Screenshot 2023-12-18 at 4 26 13 PM](https://github.com/chanzuckerberg/cryoet-data-portal/assets/475208/4fe6f130-707a-4f61-8ea9-ee463bf88d48)

**Comment by junxini** [comment]
From the FAQ page, i clicked on "Browse Data" in the top navigation bar today and got this error that persisted:

https://github.com/chanzuckerberg/cryoet-data-portal/assets/98626158/6cec3397-91a3-4df7-82f6-ae55cdbf6b98

**Comment by lauramarcos** [comment]
this no longer reproducible, hopefully does not show up again.. thank you all!!
